backend:
  name: github
  repo: xiaochai-123/juhuo
  branch: main
  base_url: https://juhuo.pages.dev
  auth_endpoint: /api/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    format: "toml-frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "分类", name: "categories", widget: "list", default: ["分类"] }
      - { label: "标签", name: "tags", widget: "list", default: ["标签"] }
      - { label: "权重", name: "weight", widget: "number", default: 1 }
      - { label: "轮播图", name: "carousel", widget: "boolean", default: false }
      - label: "封面图"
        name: "images"
        widget: "list"
        field: { label: "图片", name: "url", widget: "image" }
        default: []
        max: 1
      - { label: "描述", name: "description", widget: "string" }
      - { label: "数学公式", name: "math", widget: "boolean", default: false }
      - { label: "正文", name: "body", widget: "markdown" }